export declare const isLink: (data: string) => boolean;
export declare const isBool: (data: string) => boolean;
export declare const isValue: (data: string) => boolean;
export declare const hasOn: (data: string) => boolean;
export declare const sliceOn: (data: string) => string;
export declare const isMarker: (data: string, marker: string) => boolean;
export declare const hasMarker: (data: string, marker: string) => boolean;
export declare const includes: (item: string | Array<any>, search: any) => boolean;
export declare const dangerousLink: (data: string) => boolean;
export declare const removeBetween: (start: Node, end: Node) => void;
//# sourceMappingURL=tools.d.ts.map