name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Format
        run: deno fmt --check

      # - run: deno lint

      - name: Run Tests
        run: deno test -A ./scripts/test.ts
